repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
    - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
      args: [--fix, --show-fixes]
